name: Build and deploy Android APK
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          
      - name: Set up Expo
        run: npx expo-cli login --non-interactive --username Sammy970 --password flyingcars970
      
      - name: Delete node_modules
        run: rm -rf node_modules
  
      - name: Install dependencies
        run: npm install
        
      - name: Build APK
        run: |
            cd ${{ github.workspace }}
            npx react-native run-android --variant=release --no-interactive


      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/
